eca_autopost_facebook.settings:
  type: config_object
  label: 'Settings for "ECA Autopost Facebook" module'
  mapping:
    api_version:
      type: string
      label: 'Facebook API Version'

action.configuration.eca_post_facebook:
  type: mapping
  label: 'Settings for the "ECA Post in Facebook Page" action'
  mapping:
    message:
      type: string
      label: 'Content of Message to post'
    message_alternative:
      type: string
      label: 'Alternative content Message to post when message is empty'
    link:
      type: string
      label: 'Link to include in the post'
